version: "3"
name: lanparty

services:
  steamcmd:
    image: cm2network/steamcmd
    entrypoint: "/home/steam/steamcmd/steamcmd.sh +login ${STEAM_USER?'STEAM_USER must be set on .env'} ${STEAM_PASSWORD?'STEAM_PASSWORD must be set on .env'} +quit"
    tty: true
    stdin_open: true
    volumes:
      - source: volumes/steam_auth
        target: /home/steam/Steam
        type: bind
        bind:
          create_host_path: true


  counterstrike:
    image: cm2network/cs2
    network_mode: host
    restart: unless-stopped
    environment:
      STEAM_USER:
      STEAMUSER: "${STEAM_USER?'STEAM_USER must be set on .env'}"
      CS2_SERVERNAME: "changeme"       # (Set the visible name for your private server)
      CS2_PORT: 27015                  # (CS2 server listen port tcp_udp)
      CS2_LAN: "1"                     # (0 - LAN mode disabled, 1 - LAN Mode enabled)
      CS2_RCONPW: "changeme"           # (RCON password)
      CS2_PW: "salvepia"               # (CS2 server password)
      CS2_MAXPLAYERS: 10               # (Max players)
      CS2_GAMETYPE: 0                  # (Game type, see https://developer.valvesoftware.com/wiki/Counter-Strike_2/Dedicated_Servers)
      CS2_GAMEMODE: 1                  # (Game mode, see https://developer.valvesoftware.com/wiki/Counter-Strike_2/Dedicated_Servers)
      CS2_MAPGROUP: "mg_active"        # (Map pool)
      CS2_STARTMAP: "de_dust"       # (Start map)
      CS2_ADDITIONAL_ARGS: ""          # (Optional additional arguments to pass into cs2)
      CS2_BOT_DIFFICULTY: ""           # (0 - easy, 1 - normal, 2 - hard, 3 - expert)
      CS2_BOT_QUOTA: ""                # (Number of bots)
      CS2_BOT_QUOTA_MODE: ""           # (fill, competitive)
    volumes:
      - source: volumes/steam_auth
        target: /home/steam/Steam
        type: bind
        bind:
          create_host_path: true
      - source: volumes/cs2
        target: /home/steam/cs2-dedicated/
        type: bind
        bind:
          create_host_path: true